package app1;

public class D36 {
	public static void main(String[] args) {
		// All possible ways of try and catch
		try {
			
		}
		catch(ArithmeticException ex) {
			
		}
		
		
		
		try {
			
		}
		catch(ArithmeticException ex) {
			
		}
		catch(NumberFormatException ex) {
			
		}
		
		
		try {
			
		}
		catch(ArithmeticException ex) {
			
		}
		finally {
			
		}
		
		
		
		try {
			
		}
		catch(ArithmeticException | NumberFormatException | ArrayIndexOutOfBoundsException ex) {
			
		}
		
		
		// try alone not possible but with finally is possible
		// in this case we can't achieve Exception handling
		// with this we achieve in order to execute some mandatory statements in every flow
		try {
			
		}
		finally {
			
		}
	}
}
